Feature/lu 6127 selection file lambda
ONSdigital/takeon-ingestion pull request #27
Opened 2020-08-19 07:06 UTC by larissanne

2020-08-19 08:37 UTC, RyanAldy requested changes

2020-08-19 08:37 UTC, RyanAldy commented on aws-infrastructure/ingest.tf
> +  # layers = [aws_lambda_layer_version.python_layer.arn]
Delete this

2020-08-19 08:37 UTC, RyanAldy commented on lambda-ingest-selection-file/pick_up_selection.py
> +    #formtype = body[Values][formtype]
Delete commented lines

2020-08-19 08:37 UTC, RyanAldy commented on lambda-ingest-selection-file/pick_up_selection.py
> +        # error_queue(errorMessage)
We probably need to write the error message somewhere, so we'll need to add this function in and the code for it

2020-08-19 08:37 UTC, RyanAldy commented on lambda-ingest-selection-file/pick_up_selection.py
> +# write notification of success/failure to queue
May need this too?

2020-08-19 08:37 UTC, RyanAldy commented on pipeline.yml
> +        - lambda-ingest-tselection-file/
ingest-tselection, is that intentional?

2020-08-24 09:13 UTC, RyanAldy approved these changes

2020-08-24 14:29 UTC, ranjit-das commented
Tested and found that contributor is inserted into db from selection file

2020-08-25 14:26 UTC, merged