Feature/lu 7311 ingest baw trigger
ONSdigital/takeon-ingestion pull request #29
Opened 2020-09-08 10:17 UTC by mattprice-28

New queue and lambda trigger added, lambda modified to get info from sqs event

2020-09-08 10:32 UTC, dllmorgan requested changes

2020-09-08 10:32 UTC, dllmorgan commented on aws-infrastructure/ingest.tf
> +    name = "${var.environment_name}-bawingesttrigger"
Use the standardised naming convention for new resources: ${local.name_prefix}

2020-09-08 10:32 UTC, dllmorgan commented on lambda-ingest-selection-file/handler.py
> +    name = location.split('.com/')
The split will be on the / and not .com when using the S3 URI [s3://bucket-name/file]

2020-09-08 10:39 UTC, mattprice-28 commented on aws-infrastructure/ingest.tf
> +    name = "${var.environment_name}-bawingesttrigger"
Just looked through it, needs to be changed in quite a few places

2020-09-08 10:42 UTC, mattprice-28 commented on lambda-ingest-selection-file/handler.py
> +    name = location.split('.com/')
I changed it to zone/ (assuming the bucket name convention stays the same), i was worried just doing / would create a split on the initial //

2020-09-08 15:31 UTC, dllmorgan approved these changes

2020-09-09 09:51 UTC, ranjit-das approved these changes
Tested and works as per acceptance criteria. (End-to-end test with BAW can't be done at the moment because integration with BAW story will be coming later.)

2020-09-09 14:01 UTC, merged