Feature/spp 90/delayresponse
ONSdigital/takeon-ingestion pull request #32
Opened 2020-09-22 10:29 UTC by mattprice-28

PR modifying save lambda, new api call to contributor table and checking if period survey exists in db before trying to save, then after a successful save removing saved files from s3, list of retained files output to cloudwatch

2020-09-22 12:45 UTC, RyanAldy requested changes

2020-09-22 12:45 UTC, RyanAldy commented on lambda-ingest-combine-json/delay_response.py
> +def delayResponse (file_name, responseList):
Python functions should use _ and lower case rather than camel case. I think that's throughout, variable names etc

2020-09-22 13:48 UTC, sivagudur commented on lambda-ingest-combine-json/handler.py
> +        # print(request_response.content, "CONTENT")
Do we need to remove this commented code?

2020-09-22 13:58 UTC, mattprice-28 commented on lambda-ingest-combine-json/handler.py
> +        # print(request_response.content, "CONTENT")
I commented this out to stop a type error, think this chunk needs to be revisited

2020-09-22 14:18 UTC, sivagudur approved these changes
I manually tested ingestion save by dropping sdc RSI JSON files into landing zone bucket and I am able to see the following expected behaviour
Positive Scenario:
1. It is continuing in processing the responses when the given survey and period exists in the database.
2. After ingesting,  irrespective of errors it is clearing the files in S3 ingestion zone bucket (I think there are 2 separate stories to move the files into archive S3 bucket and handling dodgy errors during ingestion)
Negative Scenario:
The files are getting retained in the S3 ingestion zone bucket for a given responses where survey and period doesn't exists in the database
Observation:
When all the files are retained and this will happen only when all survey and period combinations doesn't exists in the database, it is calling business layer ingestion api with empty json [] , getting empty outcomes json[] from business layer and sending the same empty json [] to BPM queue.
Is this should be handled in Lambda by not calling business layer and not writing into BPM queue when json is empty?

2020-09-23 07:41 UTC, RyanAldy approved these changes

2020-09-23 07:46 UTC, merged